name: semgrep-rules
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
jobs:
  semgrep:
      name: semgrep-scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: returntocorp/semgrep-action@v1
          with:
            config: >-
              r/csharp.lang.security.injections.os-command.os-command-injection
